title: "RON1N01 Lab Notes"
description: " Documenting real-world experiments, tooling, and investigations across offensive and defensive security. Focused on building practical capabilities for detection, exploitation, and incident response."

# USER SITE SETTINGS
url: "https://ron1n01.com"
baseurl: ""   # must be empty for user sites

permalink: /:categories/:year/:month/:day/:title/

remote_theme: riggraz/no-style-please
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

theme_config:
  appearance: dark
  show_description: true
  date_format: "%Y-%m-%d"

author:
  name: "RON1N01"

include:
  - ".well-known"

