<link rel="shortcut icon" href="favicon.ico" type="image/x-icon">

title: "RON1N Lab Notes"
description: "Documenting experiments and insights from my journey in offensive, defensive, and cloud security.‚Äù"

# USER SITE SETTINGS
url: "https://ron1n01.com"
baseurl: ""   # must be empty for user sites

permalink: /:categories/:year/:month/:day/:title/

remote_theme: riggraz/no-style-please
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

theme_config:
  appearance: auto
  show_description: true
  date_format: "%Y-%m-%d"

author:
  name: "Daryl Spink"

include:
  - ".well-known"

